### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by SAMYAK99** [SAMYAK99/Covid_Care#1]
This is a beginner friendly task for Hactoberfest 2020 . Need Help in improving Readme.md file

**Comment by RuchikaGuntewar** [comment]
I would like to work on improving Readme.md, can yo please assign this to me and guide regarding the same?

**Comment by SAMYAK99** [comment]
Hi ! You can add all the important details like - features of the app , Tech Stack used , minimum sdk requirements , setting up of project etc...

**Comment by akhil2000mittal** [comment]
I would be happy to work on this can please assign me this?

**Comment by SAMYAK99** [comment]
Go Ahead !
