### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by SAMYAK99** [SAMYAK99/Covid_Care#2]
This is a beginner friendly task for Hactoberfest 2020 .  Integrate Splash Screen in the app with a time limit of 3 seconds

**Comment by hutomosaktikartiko** [comment]
> This is a beginner friendly task for Hactoberfest 2020 . Integrate Splash Screen in the app with a time limit of 3 seconds

do you already have a design that will be applied to the code?

**Comment by SAMYAK99** [comment]
Hi ! Splash screen should contains app name and app icon(refer to issue #5 ) in the center of the screen .

**Comment by kshitij5** [comment]
Can you assign it to me! I would do it!
