### ISSUE TITLE
Update Chat Bot Functnality 

### ISSUE THREAD

**Issue by SAMYAK99** [SAMYAK99/Covid_Care#3]
Current Version of the app has decrypted chatbot . Update The Chatbot with new URL

**Comment by anirudhbagri** [comment]
Can you give some more detail on it?

**Comment by SAMYAK99** [comment]
Currently we are using apollo chatbot which is deprecated now . 
We want  to develop a new chatbot using one of the trending technologies (for eg. dialogflow) , then put its URL in the desired section .
