### ISSUE TITLE
Integerate App Icon

### ISSUE THREAD

**Issue by SAMYAK99** [SAMYAK99/Covid_Care#5]
Currently the app has default flutter icon . Change this default icon to any new icon .

**Comment by hutomosaktikartiko** [comment]
> Currently the app has default flutter icon . Change this default icon to any new icon .

have you provided the icon that will be used?

**Comment by SAMYAK99** [comment]
You can use any relevant icon for this app   😀 . Make sure the icon is (512 px by 512 px) and it should be copyright free

**Comment by hutomosaktikartiko** [comment]
![image](https://user-images.githubusercontent.com/51199036/94999668-287f1980-05e5-11eb-887c-99673cb996b3.png)
how about this ?

**Comment by SAMYAK99** [comment]
Good !

**Comment by hutomosaktikartiko** [comment]
> Good !

please check my PR
